language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -e .[tests,pipenv]
  - pip install codecov
script:
  - pytest --cov=platter --cov-report=term
after_success:
  - codecov
